services:
  postgres:
    image: 'postgres:latest'
    container_name: 'linkup-postgres'
    environment:
      - 'POSTGRES_DB=kakaotalk'
      - 'POSTGRES_PASSWORD=pqowieur!!'
      - 'POSTGRES_USER=kakaotalk'
    ports:
      - '5432:5432'
    volumes:
      - './.compose/postgres:/var/lib/postgresql/data'
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: 'linkup-rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=pqowieur!!'
      - 'RABBITMQ_DEFAULT_USER=kakaotalk'
    entrypoint: 'sh -c "rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-server"'
    ports:
      - '5672:5672'
      - '15672:15672'
      - '61613:61613'
    volumes:
      - './.compose/rabbitmq:/var/lib/rabbitmq'
  redis:
    image: 'redis:latest'
    container_name: 'linkup-redis'
    command: 'redis-server --requirepass pqowieur!!'
    ports:
      - '6379:6379'
    volumes:
      - './.compose/redis:/data'